# Adds namespace to all resources.
namespace: rancher-turtles-system

namePrefix: rancher-turtles-day2-operations-

commonLabels:
  turtles-capi.cattle.io: "day2-operations"

bases:
- ../crd
- ../rbac
- ../webhook
- ../certmanager

# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.
patchesStrategicMerge:
- webhookcainjection_patch.yaml
- manager_role_aggregation_patch.yaml

# The deployment for day2 operations references a service account
# so both of these objects are applied, if enabled via the Helm values.
# The patches below remove the service account as it gets applied with 
# the deployment and also update the role and cluster role bindings accordingly.
patches:
- target:
    kind: ServiceAccount
  patch: |
    $patch: delete
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: rancher-turtles-day2-operations-manager
- target:
    kind: RoleBinding
    labelSelector: "app.kubernetes.io/instance=leader-election-rolebinding"
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: rancher-turtles-day2-operations-manager
    - op: replace
      path: /subjects/0/namespace
      value: rancher-turtles-system
- target:
    kind: ClusterRoleBinding
    labelSelector: "app.kubernetes.io/instance=manager-rolebinding"
  patch: |-
    - op: replace
      path: /subjects/0/name
      value: rancher-turtles-day2-operations-manager
    - op: replace
      path: /subjects/0/namespace
      value: rancher-turtles-system

# patchesStrategicMerge:
# - manager_role_aggregation_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# - path: manager_webhook_patch.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
# - path: webhookcainjection_patch.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER' prefix.
# Uncomment the following replacements to add the cert-manager CA injection annotations
replacements:
 - source: # Add cert-manager annotation to ValidatingWebhookConfiguration, MutatingWebhookConfiguration and CRDs
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: serving-cert # this name should match the one in certificate.yaml
     fieldPath: .metadata.namespace # namespace of the certificate CR
   targets:
     - select:
         kind: ValidatingWebhookConfiguration
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 0
         create: true
     - select:
         kind: MutatingWebhookConfiguration
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 0
         create: true
     - select:
         kind: CustomResourceDefinition
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 0
         create: true
 - source:
     kind: Certificate
     group: cert-manager.io
     version: v1
     name: serving-cert # this name should match the one in certificate.yaml
     fieldPath: .metadata.name
   targets:
     - select:
         kind: ValidatingWebhookConfiguration
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 1
         create: true
     - select:
         kind: MutatingWebhookConfiguration
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 1
         create: true
     - select:
         kind: CustomResourceDefinition
       fieldPaths:
         - .metadata.annotations.[cert-manager.io/inject-ca-from]
       options:
         delimiter: '/'
         index: 1
         create: true
 - source: # Add cert-manager annotation to the webhook Service
     kind: Service
     version: v1
     name: webhook-service
     fieldPath: .metadata.name # namespace of the service
   targets:
     - select:
         kind: Certificate
         group: cert-manager.io
         version: v1
       fieldPaths:
         - .spec.dnsNames.0
         - .spec.dnsNames.1
       options:
         delimiter: '.'
         index: 0
         create: true
 - source:
     kind: Service
     version: v1
     name: webhook-service
     fieldPath: .metadata.namespace # namespace of the service
   targets:
     - select:
         kind: Certificate
         group: cert-manager.io
         version: v1
       fieldPaths:
         - .spec.dnsNames.0
         - .spec.dnsNames.1
       options:
         delimiter: '.'
         index: 1
         create: true

vars:
  - name: SERVICE_NAME
    objref:
      kind: Service
      version: v1
      name: webhook-service

configurations:
  - kustomizeconfig.yaml