version: 2
updates:
  # Main Go module
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      testing-dependencies:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      provider-dependencies:
        patterns:
          - "*cluster-api-provider*"
      other-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded separately.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # Test Go module
  - package-ecosystem: "gomod"
    directory: "/test"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      testing-dependencies:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      provider-dependencies:
        patterns:
          - "*cluster-api-provider*"
      other-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # ETCD backup/restore module
  - package-ecosystem: "gomod"
    directory: "exp/day2/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      testing-dependencies:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      provider-dependencies:
        patterns:
          - "*cluster-api-provider*"
      other-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore Cluster-API as its upgraded manually.
      - dependency-name: "sigs.k8s.io/cluster-api"
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # Clusterclass progressive rebase implementation
  - package-ecosystem: "gomod"
    directory: "/exp/clusterclass"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      testing-dependencies:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      provider-dependencies:
        patterns:
          - "*cluster-api-provider*"
      other-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # Examples package
  - package-ecosystem: "gomod"
    directory: "/examples"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/dependency"
    groups:
      testing-dependencies:
        patterns:
          - "github.com/onsi/ginkgo/v2"
          - "github.com/onsi/gomega"
      provider-dependencies:
        patterns:
          - "*cluster-api-provider*"
      other-dependencies:
        patterns:
          - "*"
    ignore:
      # Ignore controller-runtime as its upgraded manually.
      - dependency-name: "sigs.k8s.io/controller-runtime"
      # Ignore k8s and its transitives modules as they are upgraded manually
      # together with controller-runtime.
      - dependency-name: "k8s.io/*"
      - dependency-name: "go.etcd.io/*"
      - dependency-name: "google.golang.org/grpc"

  # Docker updates
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/build-and-release"

  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "kind/cleanup"
      - "area/build-and-release"

  # Devcontainers updates
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
