#!/bin/bash
#
# Submit new Turtles version against rancher/charts

set -ue

PREV_TURTLES_VERSION="$1" # e.g. 0.5.2-rc.3
NEW_TURTLES_VERSION="$2"
PREV_CHART_VERSION="$3" # e.g. 101.2.0
NEW_CHART_VERSION="$4"
REPLACE="$5" # remove previous version if `true`, otherwise add new

if [ -z "${GITHUB_WORKSPACE:-}" ]; then
	CHARTS_DIR="$(dirname -- "$0")/../../../charts"
else
	CHARTS_DIR="${GITHUB_WORKSPACE}/charts"
fi

pushd "${CHARTS_DIR}" >/dev/null

if [ ! -e ~/.gitconfig ]; then
	git config --global user.name "highlander-ci-bot"
	git config --global user.email highlander-ci@proton.me
fi

if [ ! -f bin/charts-build-scripts ]; then
	make pull-scripts
fi

find ./packages/rancher-turtles/ -type f -exec sed -i -e "s/${PREV_TURTLES_VERSION}/${NEW_TURTLES_VERSION}/g" {} \;
find ./packages/rancher-turtles/ -type f -exec sed -i -e "s/version: ${PREV_CHART_VERSION}/version: ${NEW_CHART_VERSION}/g" {} \;
find ./packages/rancher-turtles/ -type f -exec sed -i -e "/doNotRelease: false/d" {} \;

if [ "${REPLACE}" == "true" ] && grep -q "rancher-turtles:" release.yaml; then
	sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_TURTLES_VERSION}/${NEW_CHART_VERSION}+up${NEW_TURTLES_VERSION}/g" release.yaml
else
	if grep -q "rancher-turtles:" release.yaml; then
		sed -i -e "s/${PREV_CHART_VERSION}+up${PREV_TURTLES_VERSION}/${PREV_CHART_VERSION}+up${PREV_TURTLES_VERSION}\n  - ${NEW_CHART_VERSION}+up${NEW_TURTLES_VERSION}/g" release.yaml
	else
		cat <<<"
rancher-turtles:
- ${PREV_CHART_VERSION}+up${PREV_TURTLES_VERSION}
- ${NEW_CHART_VERSION}+up${NEW_TURTLES_VERSION}" >>release.yaml
		# remove empty line above rancher-turtles
		sed -i -z -e "s/[[:space:]]*\nrancher-turtles:/\nrancher-turtles:/g" release.yaml
	fi
fi

git add packages/rancher-turtles release.yaml
git commit -m "Updating to Turtles v${NEW_TURTLES_VERSION}"

if [ "${REPLACE}" == "true" ]; then
	for i in rancher-turtles; do
		CHART=$i VERSION=${PREV_CHART_VERSION}+up${PREV_TURTLES_VERSION} make remove
	done
fi

PACKAGE=rancher-turtles make charts
git add assets/rancher-turtles* charts/rancher-turtles* index.yaml
git commit -m "Autogenerated changes for Turtles v${NEW_TURTLES_VERSION}"

popd >/dev/null
