apiVersion: fleet.cattle.io/v1alpha1
kind: HelmApp
metadata:
  name: calico-cni
spec:
  helm:
    version: v3.29.3
    releaseName: projectcalico
    repo: https://docs.tigera.io/calico/charts
    chart: tigera-operator
    templateValues:
      installation: |-
        cni:
          type: Calico
        calicoNetwork:
          bgp: Disabled
          mtu: 1350
          ipPools:
            ${- range $cidr := .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks }
            - cidr: "${ $cidr }"
              encapsulation: VXLAN${- end}
  diff:
    comparePatches:
    - apiVersion: operator.tigera.io/v1
      kind: Installation
      name: default
      operations:
      - {"op":"remove", "path":"/spec/kubernetesProvider"}
  insecureSkipTLSVerify: true
  targets:
  - clusterSelector:
      matchLabels:
        cni: calico
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values:
          - azure-rke2-example
          - docker-kubeadm-example
          - docker-rke2-example
          - etcd-snapshot-restore
          - vsphere-kubeadm-example
          - vsphere-rke2-example
