namespace: "{{ .Values.namespace }}"
images:
- name: controller
  newName: "{{ .Values.image.repository }}"
  newTag: "{{ .Values.image.tag }}"
namePrefix: rancher-turtles-
resources:
- ../rbac
- ../crd
