apiVersion: cluster.x-k8s.io/v1beta2
kind: ClusterClass
metadata:
  name: azure-aks-example
spec:
  controlPlane:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureASOManagedControlPlaneTemplate
      name: aks-control-plane
  infrastructure:
    templateRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: AzureASOManagedClusterTemplate
      name: aks-cluster
  workers:
    machinePools:
      - class: default-system
        bootstrap:
          templateRef:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: RKE2ConfigTemplate
            name: aks-dummy-system
        infrastructure:
          templateRef:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedMachinePoolTemplate
            name: aks-default-system
      - class: default-worker
        bootstrap:
          templateRef:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
            kind: RKE2ConfigTemplate
            name: aks-dummy-worker
        infrastructure:
          templateRef:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedMachinePoolTemplate
            name: aks-default-worker
  variables:
    - name: location
      required: true
      schema:
        openAPIV3Schema:
          description: "The Azure location where the Cluster will be created."
          type: string
          enum:
            - australiaeast
            - eastus
            - eastus2
            - francecentral
            - germanywestcentral
            - northcentralus
            - northeurope
            - switzerlandnorth
            - uksouth
            - westeurope
            - westus2
    - name: resourceGroup
      required: true
      schema:
        openAPIV3Schema:
          description: "The Azure Resource Group where the Cluster will be created."
          type: string
    - name: asoCredentialSecretName
      required: true
      schema:
        openAPIV3Schema:
          description: "The ASO credential secret name used to authenticate with Azure."
          type: string
          default: "aso-credential"
    - name: autoUpgradeChannel
      required: true
      schema:
        openAPIV3Schema:
          description: "The Cluster auto-upgrade channel. Use 'none' to disable auto upgrades."
          type: string
          enum:
            - none
            - patch
            - stable
            - rapid
          default: stable
    - name: sku
      required: true
      schema:
        openAPIV3Schema:
          description: "The size of the VMs in the node pool"
          type: string
          default: Standard_D2s_v3
  patches:
    - name: azureASOManagedClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: replace
              path: "/spec/template/spec"
              valueFrom:
                template: |
                  resources:
                  - apiVersion: resources.azure.com/v1api20200601
                    kind: ResourceGroup
                    metadata:
                      name: "{{ .resourceGroup }}"
                      annotations:
                        serviceoperator.azure.com/credential-from: "{{ .asoCredentialSecretName }}"
                    spec:
                      location: "{{ .location }}"
    - name: azureASOManagedControlPlaneTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: replace
              path: "/spec/template/spec"
              valueFrom:
                template: |
                  version: "{{ .builtin.cluster.topology.version }}"
                  resources:
                  - apiVersion: containerservice.azure.com/v1api20240901
                    kind: ManagedCluster
                    metadata:
                      name: "{{ .builtin.cluster.name }}"
                      annotations:
                        serviceoperator.azure.com/credential-from: "{{ .asoCredentialSecretName }}"
                    spec:
                      owner:
                        name: "{{ .resourceGroup }}"
                      dnsPrefix: "{{ .builtin.cluster.name }}"
                      location: "{{ .location }}"
                      identity:
                        type: SystemAssigned
                      servicePrincipalProfile:
                        clientId: msi
                      networkProfile:
                        networkPlugin: azure
                      autoUpgradeProfile:
                        upgradeChannel: "{{ .autoUpgradeChannel }}"
    - name: azureASOManagedMachinePoolTemplate-system
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedMachinePoolTemplate
            matchResources:
              machinePoolClass:
                names:
                  - default-system
          jsonPatches:
            - op: replace
              path: "/spec/template/spec"
              valueFrom:
                template: |
                  resources:
                  - apiVersion: containerservice.azure.com/v1api20240901
                    kind: ManagedClustersAgentPool
                    metadata:
                      name: "{{ .builtin.cluster.name }}-system"
                      annotations:
                        serviceoperator.azure.com/credential-from: "{{ .asoCredentialSecretName }}"
                    spec:
                      azureName: "system"
                      owner:
                        name: "{{ .builtin.cluster.name }}"
                      mode: System
                      type: VirtualMachineScaleSets
                      vmSize: "{{ .sku }}"
    - name: azureASOManagedMachinePoolTemplate-worker
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: AzureASOManagedMachinePoolTemplate
            matchResources:
              machinePoolClass:
                names:
                  - default-worker
          jsonPatches:
            - op: replace
              path: "/spec/template/spec"
              valueFrom:
                template: |
                  resources:
                  - apiVersion: containerservice.azure.com/v1api20240901
                    kind: ManagedClustersAgentPool
                    metadata:
                      name: "{{ .builtin.cluster.name }}-worker"
                      annotations:
                        serviceoperator.azure.com/credential-from: "{{ .asoCredentialSecretName }}"
                    spec:
                      azureName: "worker"
                      owner:
                        name: "{{ .builtin.cluster.name }}"
                      mode: User
                      type: VirtualMachineScaleSets
                      vmSize: "{{ .sku }}"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedControlPlaneTemplate
metadata:
  name: aks-control-plane
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedClusterTemplate
metadata:
  name: aks-cluster
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedMachinePoolTemplate
metadata:
  name: aks-default-system
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureASOManagedMachinePoolTemplate
metadata:
  name: aks-default-worker
spec:
  template:
    spec: {}
---
# These RKE2ConfigTemplates are only referenced to fulfill the CAPI contract.
# This requires however the cluster-api-provider-rke2 to be installed.
# It can be replaced by KubeadmConfigTemplates.
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: RKE2ConfigTemplate
metadata:
  name: aks-dummy-worker
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta2
kind: RKE2ConfigTemplate
metadata:
  name: aks-dummy-system
spec:
  template:
    spec: {}
