---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - catalog.cattle.io
  resources:
  - uiplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - watch
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - clusterregistrationtokens
  - clusters
  - clusters/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.cattle.io
  resources:
  - clusterregistrationtokens/status
  - settings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - provisioning.cattle.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resourceNames:
  - rancher-turtles-manager-role
  resources:
  - clusterroles
  verbs:
  - get
  - list
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - capiproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - capiproviders/finalizers
  verbs:
  - update
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - capiproviders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - clusterctlconfigs
  - clusterctlconfigs/status
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - clusterctlconfigs/finalizers
  verbs:
  - get
  - list
  - patch
  - update
  - watch
