apiVersion: fleet.cattle.io/v1alpha1
kind: HelmOp
metadata:
  name: azure-ccm
spec:
  helm:
    releaseName: cloud-provider-azure
    repo: https://raw.githubusercontent.com/kubernetes-sigs/cloud-provider-azure/master/helm/repo
    chart: cloud-provider-azure
    templateValues:
      infra: |-
        clusterName: ${ .ClusterValues.Cluster.metadata.name }
      cloudControllerManager: |-
        clusterCIDR: ${ .ClusterValues.Cluster.spec.clusterNetwork.pods.cidrBlocks | join "," }
        caCertDir: /etc/ssl
        hostNetworking: true
        nodeSelector:
          ${- if contains "KubeadmControlPlane" ( .ClusterValues | quote ) }
          node-role.kubernetes.io/control-plane: ""
          ${- else }
          node-role.kubernetes.io/control-plane: "true"
          ${- end }
  insecureSkipTLSVerify: true
  targets:
  - clusterSelector:
      matchLabels:
        cloud-provider: azure
      matchExpressions:
      - key: clusterclass-name.fleet.addons.cluster.x-k8s.io
        operator: In
        values: [azure-rke2-example, azure-kubeadm-example]
