---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cluster.x-k8s.io
  resources:
  - clusterclasses
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.turtles-capi.cattle.io
  resources:
  - clusterupgradegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.turtles-capi.cattle.io
  resources:
  - clusterupgradegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rollout.turtles-capi.cattle.io
  resources:
  - clusterupgradegroupss/finalizers
  verbs:
  - update
