apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: vsphere-rke2-example
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: RKE2ControlPlaneTemplate
      name: vsphere-rke2-example-controlplane
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        name: vsphere-rke2-example-controlplane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: VSphereClusterTemplate
      name: vsphere-rke2-example
  workers:
    machineDeployments:
    - class: vsphere-rke2-example-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: RKE2ConfigTemplate
            name: vsphere-rke2-example-worker
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: VSphereMachineTemplate
            name: vsphere-rke2-example-worker
  variables:
  - name: sshKey
    required: false
    schema:
      openAPIV3Schema:
        description: Public key to SSH onto the cluster nodes.
        type: string
  - name: controlPlaneIpAddr
    required: true
    schema:
      openAPIV3Schema:
        description: Floating VIP for the control plane.
        type: string
  - name: controlPlanePort
    required: true
    schema:
      openAPIV3Schema:
        description: Port for the control plane endpoint.
        type: integer
  - name: kubeVIPInterface
    required: true
    schema:
      openAPIV3Schema:
        description: The interface name used by kube-vip in ARP mode.
        type: string
        default: eth0
  - name: vSphereTLSThumbprint
    required: true
    schema:
      openAPIV3Schema:
        description: "sha256 thumbprint of the vcenter certificate: openssl x509 -sha256 -fingerprint -in ca.crt -noout"
        type: string
  - name: vSphereClusterIdentityName
    required: true
    schema:
      openAPIV3Schema:
        description: The VSphereClusterIdentity resource name referencing the credentials to create the Cluster.
        type: string
        default: cluster-identity
  - name: vSphereServer
    required: true
    schema:
      openAPIV3Schema:
        description: The vCenter server IP or FQDN.
        type: string
  - name: vSphereDataCenter
    required: true
    schema:
      openAPIV3Schema:
        description: The vSphere datacenter to deploy the Cluster on.
        type: string
  - name: vSphereResourcePool
    required: true
    schema:
      openAPIV3Schema:
        description: The vSphere resource pool for your VMs.
        type: string
  - name: vSphereDataStore
    required: true
    schema:
      openAPIV3Schema:
        description: The vSphere datastore to deploy the Cluster on.
        type: string
  - name: vSphereNetwork
    required: true
    schema:
      openAPIV3Schema:
        description: The VM network to deploy the Cluster on.
        type: string
  - name: vSphereFolder
    required: true
    schema:
      openAPIV3Schema:
        description: The VM folder for your VMs. Set to "" to use the root vSphere folder.
        type: string
  - name: vSphereTemplate
    required: true
    schema:
      openAPIV3Schema:
        description: The VM template to use for your Cluster.
        type: string
  patches:
  - name: infraCluster
    definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/controlPlaneEndpoint
        valueFrom:
          template: |
            host: '{{ .controlPlaneIpAddr }}'
            port: {{ .controlPlanePort }}
      - op: add
        path: /spec/template/spec/identityRef/name
        valueFrom:
          variable: vSphereClusterIdentityName
      - op: add
        path: /spec/template/spec/server
        valueFrom:
          variable: vSphereServer
      - op: add
        path: /spec/template/spec/thumbprint
        valueFrom:
          variable: vSphereTLSThumbprint
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereClusterTemplate
        matchResources:
          infrastructureCluster: true
  - name: vsphereMachineTemplate
    definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec
        valueFrom:
          template: |
            cloneMode: linkedClone
            datacenter: '{{ .vSphereDataCenter }}'
            datastore: '{{ .vSphereDataStore }}'
            diskGiB: 25
            folder: '{{ .vSphereFolder }}'
            memoryMiB: 8192
            network:
              devices:
              - dhcp4: true
                networkName: '{{ .vSphereNetwork }}'
            numCPUs: 2
            os: Linux
            powerOffMode: trySoft
            resourcePool: '{{ .vSphereResourcePool }}'
            server: '{{ .vSphereServer }}'
            storagePolicyName: ''
            template: '{{ .vSphereTemplate }}'
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        matchResources:
          controlPlane: true
    - jsonPatches:  
      - op: add
        path: /spec/template/spec
        valueFrom:
          template: |
            cloneMode: linkedClone
            datacenter: '{{ .vSphereDataCenter }}'
            datastore: '{{ .vSphereDataStore }}'
            diskGiB: 25
            folder: '{{ .vSphereFolder }}'
            memoryMiB: 8192
            network:
              devices:
              - dhcp4: true
                networkName: '{{ .vSphereNetwork }}'
            numCPUs: 2
            os: Linux
            powerOffMode: trySoft
            resourcePool: '{{ .vSphereResourcePool }}'
            server: '{{ .vSphereServer }}'
            storagePolicyName: ''
            template: '{{ .vSphereTemplate }}'
      selector:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: VSphereMachineTemplate
        matchResources:
          machineDeploymentClass:
            names: 
            - vsphere-rke2-example-worker
  - name: rke2ControlPlaneTemplate
    definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/files
        valueFrom:
          template: |
            - path: "/var/lib/rancher/rke2/server/manifests/kube-vip.yaml"
              owner: "root:root"
              permissions: "0640"
              content: |
                apiVersion: v1
                kind: Pod
                metadata:
                  creationTimestamp: null
                  name: kube-vip
                  namespace: kube-system
                spec:
                  tolerations:
                  - effect: NoSchedule
                    key: node.cloudprovider.kubernetes.io/uninitialized
                    operator: Exists
                  - effect: NoSchedule
                    key: node.kubernetes.io/not-ready
                    operator: Exists
                  containers:
                  - args:
                    - manager
                    env:
                    - name: vip_arp
                      value: "true"
                    - name: port
                      value: "{{ .controlPlanePort }}"
                    - name: vip_nodename
                      valueFrom:
                        fieldRef:
                          fieldPath: spec.nodeName
                    - name: vip_interface
                      value: "{{ .kubeVIPInterface }}"
                    - name: vip_subnet
                      value: "32"
                    - name: dns_mode
                      value: first
                    - name: cp_enable
                      value: "true"
                    - name: cp_namespace
                      value: kube-system
                    - name: svc_enable
                      value: "true"
                    - name: svc_leasename
                      value: plndr-svcs-lock
                    - name: vip_leaderelection
                      value: "true"
                    - name: vip_leasename
                      value: plndr-cp-lock
                    - name: vip_leaseduration
                      value: "5"
                    - name: vip_renewdeadline
                      value: "3"
                    - name: vip_retryperiod
                      value: "1"
                    - name: address
                      value: "{{ .controlPlaneIpAddr }}"
                    - name: prometheus_server
                      value: :2112
                    image: ghcr.io/kube-vip/kube-vip:v0.9.1
                    imagePullPolicy: IfNotPresent
                    name: kube-vip
                    resources: {}
                    securityContext:
                      capabilities:
                        add:
                        - NET_ADMIN
                        - NET_RAW
                        drop:
                        - ALL
                    volumeMounts:
                    - mountPath: /etc/kubernetes/admin.conf
                      name: kubeconfig
                  hostAliases:
                  - hostnames:
                    - kubernetes
                    ip: 127.0.0.1
                  hostNetwork: true
                  volumes:
                  - hostPath:
                      path: /etc/rancher/rke2/rke2.yaml
                    name: kubeconfig
      - op: add
        path: /spec/template/spec/agentConfig/additionalUserData
        valueFrom:
          template: |-
            config: |-
              users:
                - name: capv
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh-authorized-keys:
                  - {{ .sshKey }}   
      selector:
        apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        kind: RKE2ControlPlaneTemplate
        matchResources:
          controlPlane: true
  - name: rke2ConfigTemplate
    definitions:
    - jsonPatches:
      - op: add
        path: /spec/template/spec/agentConfig/additionalUserData
        valueFrom:
          template: |-
            config: |-
              users:
                - name: capv
                  sudo: ALL=(ALL) NOPASSWD:ALL
                  ssh-authorized-keys:
                  - {{ .sshKey }}   
      selector:
        apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
        kind: RKE2ConfigTemplate
        matchResources:
          machineDeploymentClass:
            names:
            - vsphere-rke2-example-worker
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereClusterTemplate
metadata:
  name: vsphere-rke2-example
spec:
  template:
    spec:
      identityRef:
        kind: VSphereClusterIdentity
        name: cluster-identity
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: RKE2ControlPlaneTemplate
metadata:
  name: vsphere-rke2-example-controlplane
spec:
  template:
    spec:
      agentConfig: {}
      serverConfig:
        cni: none
        cloudProviderName: external
        disableComponents:
          kubernetesComponents:
          - cloudController
      rolloutStrategy:
        type: "RollingUpdate"
        rollingUpdate:
          maxSurge: 1
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: RKE2ConfigTemplate
metadata:
  name: vsphere-rke2-example-worker
spec: 
  template:
    spec:
      agentConfig:
        kubelet:
          extraArgs:
            - "--cloud-provider=external"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vsphere-rke2-example-controlplane
spec:
  template:
    # Hardcoded values will not be respected.
    # Configure everything via patch.
    spec:
      template: 'set-by-patch'
      network:
       devices: []
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  name: vsphere-rke2-example-worker
spec:
  template:
    # Hardcoded values will not be respected.
    # Configure everything via patch.
    spec:
      template: 'set-by-patch'
      network:
       devices: []
