{{- if index .Values "providers" "addonFleet" "enabled" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "providers" "addonFleet" "namespace" }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-addon-config
  namespace: {{ index .Values "providers" "addonFleet" "namespace" }}
data:
  manifests: |-
    apiVersion: addons.cluster.x-k8s.io/v1alpha1
    kind: FleetAddonConfig
    metadata:
      name: fleet-addon-config
    spec:
      config:
        featureGates:
          configMap:
            ref:
              kind: ConfigMap
              apiVersion: v1
              name: rancher-config
              namespace: cattle-system
          experimentalOciStorage: true
          experimentalHelmOps: true
      clusterClass:
        patchResource: true
        setOwnerReferences: true
      cluster:
        agentNamespace: cattle-fleet-system
        applyClassGroup: true
        patchResource: true
        setOwnerReferences: true
        hostNetwork: true
        selector:
          matchLabels:
            cluster-api.cattle.io/rancher-auto-import: "true"
          matchExpressions:
            - key: cluster-api.cattle.io/disable-fleet-auto-import
              operator: DoesNotExist
        namespaceSelector:
          matchLabels:
            cluster-api.cattle.io/rancher-auto-import: "true"
          matchExpressions:
            - key: cluster-api.cattle.io/disable-fleet-auto-import
              operator: DoesNotExist
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cappf-controller-psa
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: fleet-controller-psa
    subjects:
    - kind: ServiceAccount
      name: caapf-controller-manager
      namespace: {{ .Values.providers.addonFleet.namespace }}
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: fleet
  namespace: {{ index .Values "providers" "addonFleet" "namespace" }}
spec:
  name: rancher-fleet
  type: addon
{{- if index .Values  "providers" "addonFleet" "version" }}
  version: {{ index .Values "providers" "addonFleet" "version" }}
{{- end }}
{{- if index .Values  "providers" "addonFleet" "enableAutomaticUpdate" }}
  enableAutomaticUpdate: {{ index .Values "providers" "addonFleet" "enableAutomaticUpdate" }}
{{- end }}
{{- if index .Values  "providers" "addonFleet" "features" }}
  features:
    machinePool: {{ index .Values "providers" "addonFleet" "features" "machinePool" }}
    clusterResourceSet: {{ index .Values "providers" "addonFleet" "features" "clusterResourceSet" }}
    clusterTopology: {{ index .Values "providers" "addonFleet" "features" "clusterTopology" }}
{{- end }}
{{- if index .Values  "providers" "addonFleet" "variables" }}
  variables:
  {{- range $key, $val := .Values.providers.addonFleet.variables }}
    {{ $key }}: "{{ $val }}"
  {{- end }}
{{- end }}
{{- if index .Values  "providers" "addonFleet" "manager" }}
  manager:
{{ toYaml (index .Values "providers" "addonFleet" "manager") | nindent 4 }}
{{- end }}
{{- if or (index .Values "providers" "addonFleet" "credentials") }}
  credentials:
    name: {{ index .Values "providers" "addonFleet" "credentials" "name" }}
    namespace: {{ index .Values "providers" "addonFleet" "credentials" "namespace" }}
{{- end }}
{{- if or (index .Values "providers" "addonFleet" "configSecret") }}
  configSecret:
    name: {{ index .Values "providers" "addonFleet" "configSecret" "name" }}
    namespace: {{ index .Values "providers" "addonFleet" "configSecret" "namespace" }}
{{- end }}
{{- if index .Values "providers" "addonFleet" "fetchConfig" }}
  fetchConfig:
    {{- if index .Values "providers" "addonFleet" "fetchConfig" "url" }}
    url: {{ index .Values "providers" "addonFleet" "fetchConfig" "url" }}
    {{- end }}
    {{- if index .Values "providers" "addonFleet" "fetchConfig" "oci" }}
    oci: {{ index .Values "providers" "addonFleet" "fetchConfig" "oci" }}
    {{- end }}
{{- end }}
  additionalManifests:
    name: fleet-addon-config
    namespace: {{ index .Values "providers" "addonFleet" "namespace" }}
{{- end }}
