{{- if index .Values "cluster-api-operator" "cluster-api" "enabled" }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
---
apiVersion: turtles-capi.cattle.io/v1alpha1
kind: CAPIProvider
metadata:
  name: cluster-api
  namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
spec:
  name: cluster-api
  type: core
  enableAutomaticUpdate: {{ index .Values "cluster-api-operator" "cluster-api" "core" "enableAutomaticUpdate" }}
{{- if index .Values "cluster-api-operator" "cluster-api" "core" "version" }}
  version: {{ index .Values "cluster-api-operator" "cluster-api" "core" "version" }}
{{- end }}
  additionalManifests:
    name: capi-additional-rbac-roles
    namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  configSecret:
{{- if index .Values "cluster-api-operator" "cluster-api" "configSecret" "name" }}
    name: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "name" }}
{{ else }}
    name: {{ index .Values "cluster-api-operator" "cluster-api" "configSecret" "defaultName" }}
{{- end }}
  fetchConfig:
    {{- if index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "url" }}
    url: {{ index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "url" }}
    {{- else if index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "selector" }}
    selector: {{ index .Values "cluster-api-operator" "cluster-api" "core" "fetchConfig" "selector" | toYaml | nindent 6 }}
    {{- end }}
{{- if index .Values "cluster-api-operator" "cluster-api" "core" "imageUrl" }}
  deployment:
    containers:
      - name: manager
        imageUrl: {{ index .Values "cluster-api-operator" "cluster-api" "core" "imageUrl" }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: capi-additional-rbac-roles
  namespace: {{ index .Values "cluster-api-operator" "cluster-api" "core" "namespace" }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-weight": "2"
data: 
  manifests: |-
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: provisioning-rke-machine-cattle-io
      labels:
        cluster.x-k8s.io/aggregate-to-manager: "true"
    rules:
      - apiGroups: ["rke-machine.cattle.io"]
        resources: ["*"]
        verbs: ["*"]
{{- end }}
