apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregated-manager-role
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rancher-turtles-exp/aggregate-to-manager: "true"
rules: []