kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: capi-test
nodes:
- role: control-plane
  image: kindest/node:v1.34.0
  extraMounts:
    - hostPath: /var/run/docker.sock
      containerPath: /var/run/docker.sock
  extraPortMappings:
  # Gitea test Nodeport
  - containerPort: 30001
    hostPort: 30001
    protocol: TCP
  # Rancher test Nodeport
  - containerPort: 30002
    hostPort: 30002
    protocol: TCP
