name: Cleanup e2e images

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

env:
  ORG: rancher
  REPO: turtles
  PACKAGE: turtles-e2e

jobs:
  delete_old_versions:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run delete old versions script
        run: ./scripts/cleanup-test-images.sh ${{ env.ORG }} ${{ env.REPO }} ${{ env.PACKAGE }} ${{ secrets.GITHUB_TOKEN }}
