name: Run short e2e tests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  MANAGEMENT_CLUSTER_ENVIRONMENT: "isolated-kind"
  GINKGO_LABEL_FILTER: "short"
  TAG: v0.0.1
  SOURCE_REPO: https://github.com/${{ github.event.pull_request.head.repo.full_name }}

jobs:
  e2e:
    runs-on: runs-on,runner=4cpu-linux-x64,run-id=${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
      - name: setupGo
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Display docker version
        run: docker version
      - name: Run e2e tests
        run: make test-e2e
      - name: Collect run artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts
          path: _artifacts
