on:
  workflow_call:

permissions:
  contents: read
  packages: write

env:
  # AWS Credentials
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-west-2
  # Test image tag to clean
  TAG: v0.0.1

jobs:
  e2e-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Install eksctl
        run: |
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          EKSCTL_VERSION=0.225.0
          EXPECTED_SHA256_AMD64=041ad321cafd82596b33562f1e95a8c1035a9e0b2e95e9f2bcd2ada7219def83 # immutable hash for v0.225.0 AMD64

          curl -sLO "https://github.com/eksctl-io/eksctl/releases/download/v$EKSCTL_VERSION/eksctl_$PLATFORM.tar.gz"
          echo "$EXPECTED_SHA256_AMD64  eksctl_Linux_amd64.tar.gz" | sha256sum --check

          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

          sudo mv /tmp/eksctl /usr/local/bin
      - name: Cleanup EKS Resources
        run: |
          ./scripts/ekstcl-e2e-cleanup.sh
      - name: Cleanup Azure Resources
        if: ${{ always() }}
        uses: rancher/azure-janitor@90a1ba53f7e37ad1e1a20455efe355c06849d84e # v0.1.2
        with:
          resource-groups: highlander-e2e*
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID}}
          commit: true
      - name: Cleanup GCP Resources
        if: ${{ always() }}
        uses: rancher/gcp-janitor@a26ad042cc51fee265a080d862af88e5c3b11bc0 # v0.1.0
        with:
          credentials-json: ${{ secrets.GCP_CREDENTIALS }}
          zones: ${{ secrets.GCP_ZONE }}
          project-id: ${{ secrets.GCP_PROJECT }}
          age-in-hours: 6
          resource-label-key: ${{ secrets.GCP_LABEL_KEY }}
          resource-label-value: ${{ secrets.GCP_LABEL_VALUE }}
      - name: Cleanup e2e test image
        if: ${{ always() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /orgs/rancher/packages/container/turtles-e2e/versions |
            jq -r ".[] | select( .metadata.container.tags | contains([\"$TAG\"])) | .url" |
            while read -r URL; do
              gh api --method DELETE \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                "$URL"
            done
