name: Update Core CAPI components manifest
on:
  workflow_dispatch:
    inputs:
      capi_version:
        type: string
        description: CAPI Core version (ex. 'v1.2.3')
        required: false


env:
  TURTLES_REF: "${{ github.ref_name }}"
  GH_TOKEN: "${{ github.token }}"

jobs:
  create-core-capi-turtles-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98 # v5
        with:
          fetch-depth: 0

      - name: Configure the committer
        run: |
          user_id=$(gh api "/users/$APP_USER" --jq .id)
          git config --global user.name "$APP_USER"
          git config --global user.email "${user_id}+${APP_USER}@users.noreply.github.com"
        env:
          APP_USER: "${{ github.actor }}"

      - name: Run script to fetch components manifest
        run: |
          echo "CAPI_VERSION=${{ inputs.capi_version }}" >> $GITHUB_ENV
          BRANCH="fetch-core-capi-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -b "$BRANCH" "$TURTLES_REF"
          CAPI_MANIFEST_UPDATE_VERSION=$CAPI_VERSION make update-core-capi-manifest
          git add charts/rancher-turtles
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "SKIP_PUSH=true" >> $GITHUB_ENV
          else
            git commit -m "chore: embed core CAPI ${CAPI_VERSION} in Turtles chart"
            echo "SKIP_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Push and create pull request
        if: env.SKIP_PUSH == 'false'
        run: |
          git push origin "$BRANCH"
          body="This PR fetches core CAPI $CAPI_VERSION components manifest from release and embeds the template in the Turtles chart for a simplified air-gapped installation."

          gh pr create \
            --title "chore: embed core CAPI provider $CAPI_VERSION manifest in chart" \
            --body "$body" \
            --head "${{ github.repository_owner }}:$BRANCH" \
            --base "$TURTLES_REF" \
            --label "area/installation" \
            --label "kind/ci"

      - name: Collect run artifacts
        if: env.SKIP_PUSH == 'false'
        uses: actions/upload-artifact@v7
        with:
          name: fetch-core-capi-artifacts
          path: _artifacts
