name: Update Core CAPI components manifest
on:
  workflow_dispatch:
    inputs:
      capi_version:
        type: string
        description: CAPI Core version (ex. 'v1.2.3' or empty for latest)
        required: false


env:
  TURTLES_REF: "${{ github.ref_name }}"
  GH_TOKEN: "${{ github.token }}"

jobs:
  create-core-capi-turtles-pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Configure the committer
        run: |
          user_id=$(gh api "/users/$APP_USER" --jq .id)
          git config --global user.name "$APP_USER"
          git config --global user.email "${user_id}+${APP_USER}@users.noreply.github.com"
        env:
          APP_USER: "${{ github.actor }}"

      - name: Run script to fetch components manifest
        run: |
          CAPI_MANIFEST_UPDATE_VERSION=${{ inputs.capi_version }}
          if [ -z "${CAPI_MANIFEST_UPDATE_VERSION}" ]; then
            echo "Fetching latest CAPI Core version"
            CAPI_MANIFEST_UPDATE_VERSION=$(curl -s "https://api.github.com/repos/rancher-sandbox/cluster-api/releases/latest" | jq -r ".tag_name")
            echo "Found version ${CAPI_MANIFEST_UPDATE_VERSION}"
          fi
          echo "CAPI_MANIFEST_UPDATE_VERSION=${CAPI_MANIFEST_UPDATE_VERSION}" >> $GITHUB_ENV
          BRANCH="fetch-core-capi-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}"
          echo "BRANCH=${BRANCH}" >> $GITHUB_ENV
          git checkout -b "$BRANCH" "$TURTLES_REF"
          CAPI_MANIFEST_UPDATE_VERSION=${CAPI_MANIFEST_UPDATE_VERSION} make update-core-capi-manifest
          git add charts/rancher-turtles
          if git diff --cached --quiet; then
            echo "No changes detected"
            echo "SKIP_PUSH=true" >> $GITHUB_ENV
          else
            git commit -m "chore: embed core CAPI ${CAPI_MANIFEST_UPDATE_VERSION} in Turtles chart"
            echo "SKIP_PUSH=false" >> $GITHUB_ENV
          fi

      - name: Push and create pull request
        if: env.SKIP_PUSH == 'false'
        run: |
          git push origin "$BRANCH"
          body="This PR fetches core CAPI ${CAPI_MANIFEST_UPDATE_VERSION} components manifest from release and embeds the template in the Turtles chart for a simplified air-gapped installation."

          gh pr create \
            --title "chore: embed core CAPI provider ${CAPI_MANIFEST_UPDATE_VERSION} manifest in chart" \
            --body "$body" \
            --head "${{ github.repository_owner }}:$BRANCH" \
            --base "$TURTLES_REF" \
            --label "area/installation" \
            --label "kind/ci"

      - name: Collect run artifacts
        if: env.SKIP_PUSH == 'false'
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: update-core-capi-artifacts
          path: _artifacts
