name: golangci-lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, labeled, unlabeled]

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-directory:
          - ""
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: actions/setup-go@v5
        with:
          go-version: '=1.22.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: v1.56.2
          working-directory: ${{matrix.working-directory}}
          args: --timeout=5m0s
          skip-cache: true
