name: golangci-lint

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Remove all permissions from GITHUB_TOKEN except metadata.
permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: org-${{ github.repository_owner_id }}-amd64-k8s
    container: ubuntu:22.04
    strategy:
      matrix:
        working-directory:
          - ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.1.0
        with:
          go-version: '=1.22.0'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: v1.56.2
          working-directory: ${{matrix.working-directory}}
          args: --timeout=5m0s
          skip-cache: true
