name: Turtles release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write # to create releases
  id-token: write # to read vault secrets

jobs:
  publish-images:
    runs-on: [runs-on, runner=8cpu-linux-x64, "run-id=${{ github.run_id }}", image=ubuntu22-full-x64]
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0

    - name: Read Vault secrets
      uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89
      with:
        secrets: |
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials username | DOCKER_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/dockerhub/rancher/credentials password | DOCKER_PASSWORD ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials registry | PRIME_STG_REGISTRY ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials username | PRIME_STG_REGISTRY_USERNAME ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-stg-registry/credentials password | PRIME_STG_REGISTRY_PASSWORD ;
          secret/data/github/repo/${{ github.repository }}/rancher-prime-registry/credentials registry | PRIME_REGISTRY ;

    - name: Push image to DockerHub
      uses: rancher/ecm-distro-tools/actions/publish-image@5d6e63896fea85836b2fca6dfb9236bcefe2aaa5
      with:
        image: turtles
        tag: ${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        push-to-prime: false
        public-repo: rancher
        public-username: ${{ env.DOCKER_USERNAME }}
        public-password: ${{ env.DOCKER_PASSWORD }}
        make-target: push-image

    - name: Push image to staging registry
      if: ${{ !contains(github.ref_name, '-rc') }}
      uses: rancher/ecm-distro-tools/actions/publish-image@5d6e63896fea85836b2fca6dfb9236bcefe2aaa5
      with:
        image: turtles
        tag: ${{ github.ref_name }}
        platforms: linux/amd64,linux/arm64
        push-to-public: false
        prime-repo: rancher
        identity-registry: ${{ env.PRIME_REGISTRY }}
        prime-registry: ${{ env.PRIME_STG_REGISTRY }}
        prime-username: ${{ env.PRIME_STG_REGISTRY_USERNAME }}
        prime-password: ${{ env.PRIME_STG_REGISTRY_PASSWORD }}
        prime-make-target: push-prime-image

  chart-release:
    name: Helm chart release
    uses: ./.github/workflows/chart-release.yml
    needs:
    - publish-images
    with:
      tag: ${{ github.ref_name }}
      org: rancher
      image: turtles
    secrets: inherit
