name: Renovate

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Override default log level"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug
      overrideSchedule:
        description: "Override all schedules"
        required: false
        default: "false"
        type: choice
        options:
          - "false"
          - "true"
      dryRun:
        description: "Set dry-run type (null, full)"
        required: false
        default: "null"
        type: string
  schedule:
    # Run at 06:30 on every day-of-week from Monday through Friday.
    - cron: '30 6 * * 1-5'

permissions:
  contents: read
  id-token: write

jobs:
  call-workflow:
    uses: rancher/renovate-config/.github/workflows/renovate-vault.yml@922c8e762a46f551a064c44539923a3216b245be # v1.0.5
    with:
      logLevel: ${{ inputs.logLevel || 'info' }}
      overrideSchedule: ${{ github.event.inputs.overrideSchedule == 'true' && '{''schedule'':null}' || '' }}
      dryRun: ${{ github.event.inputs.dryRun || 'null' }}
    secrets: 
      override-token: ${{ secrets.RENOVATE_FORK_GH_TOKEN || '' }}
