on:
  workflow_call:
    inputs:
      MANAGEMENT_CLUSTER_ENVIRONMENT:
        description: "The infrastructure to use for the management cluster: eks, kind or isolated-kind"
        type: string
        required: true
        default: "eks"
      test_suite:
        description: "The test suite to run (i.e. path to it)"
        required: true
        type: string
      test_name:
        description: "The display name for the test"
        required: true
        type: string
      artifact_name:
        description: "The name for the uploaded artifacts"
        required: true
        type: string
      skip_resource_cleanup:
        description: Skip Management Cluster and Charts Cleanup
        default: false
        type: boolean
      skip_deletion_test:
        description: Skip deleting git repo and cluster tests
        default: false
        type: boolean

permissions:
  contents: read
  packages: write

env:
  # GitHub Credentials
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Rancher Credentials
  RANCHER_HOSTNAME: ${{ secrets.NGROK_DOMAIN }}
  RANCHER_PASSWORD: ${{ secrets.RANCHER_PASSWORD }}
  # Ngrok Credentials
  NGROK_AUTHTOKEN: ${{ secrets.NGROK_AUTHTOKEN }}
  NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
  # AWS Credentials
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SSH_KEY_NAME: ${{ secrets.AWS_SSH_KEY_NAME }}
  # GCP Credentials and Configuration
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_NETWORK_NAME: ${{ secrets.GCP_NETWORK_NAME }}
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
  # Azure Credentials
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # Cluster Configuration
  MANAGEMENT_CLUSTER_ENVIRONMENT: ${{ inputs.MANAGEMENT_CLUSTER_ENVIRONMENT }}
  SKIP_RESOURCE_CLEANUP: ${{ inputs.skip_resource_cleanup}}
  SKIP_DELETION_TEST: ${{ inputs.skip_deletion_test }}
  # Ginkgo Test Configurations
  GINKGO_LABEL_FILTER: full
  GINKGO_TESTS: ${{ github.workspace }}/${{ inputs.test_suite }}
  GINKGO_NODES: 7
  # Version Tag
  TAG: v0.0.1

jobs:
  run_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install eksctl
        run: |
          ARCH=amd64
          PLATFORM=$(uname -s)_$ARCH
          EKSCTL_VERSION=0.225.0
          EXPECTED_SHA256_AMD64=041ad321cafd82596b33562f1e95a8c1035a9e0b2e95e9f2bcd2ada7219def83 # immutable hash for v0.225.0 AMD64

          curl -sLO "https://github.com/eksctl-io/eksctl/releases/download/v$EKSCTL_VERSION/eksctl_$PLATFORM.tar.gz"
          echo "$EXPECTED_SHA256_AMD64  eksctl_$PLATFORM.tar.gz" | sha256sum --check

          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

          sudo mv /tmp/eksctl /usr/local/bin
      - name: Install aws-iam-authenticator
        run: |
          AWS_IAM_AUTHENTICATOR_VERSION=0.7.12
          EXPECTED_SHA256_AMD64=73cca6175225ac72f4e0b8b23ca214043a98097ce6047d159b1bb3abde1bfce5 # immutable hash for v0.7.12 AMD64

          curl -L -o aws-iam-authenticator "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v$AWS_IAM_AUTHENTICATOR_VERSION/aws-iam-authenticator_${AWS_IAM_AUTHENTICATOR_VERSION}_linux_amd64"
          echo "$EXPECTED_SHA256_AMD64  aws-iam-authenticator" | sha256sum --check

          chmod +x ./aws-iam-authenticator
          sudo mv ./aws-iam-authenticator /usr/local/bin

          aws-iam-authenticator version
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: setupGo
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: go.mod
      - name: Display kind version
        run: kind version
      - name: Display docker version
        run: docker version
      - name: Docker login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run e2e tests
        run: make test-e2e
      - name: Collect run artifacts
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: artifacts_${{ inputs.artifact_name }}
          path: _artifacts
      - name: Send failed status to slack
        if: failure()
        uses: slackapi/slack-github-action@af78098f536edbc4de71162a307590698245be95 # v3.0.1
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "Rancher turtles E2E test (${{ inputs.test_name }}) run failed. Job trigger by ${{ github.event_name }} event."
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": ":github:",
                          "emoji": true
                        },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
