---
name: "Updatecli: CAPI provider version management"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Apply
        run: "updatecli apply --config ./updatecli/updatecli.d"
        env:
          UPDATECLI_GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          UPDATECLI_GITHUB_ACTOR: ${{ github.actor }}
